[package]

name = "dht"
description = "Implementation of Kademlia-based DHT in Rust"
version = "0.0.1"
authors = ["Dmitry Tantsur <divius.inside@gmail.com>"]
homepage = "https://github.com/divius/rust-dht"
readme = "README.md"
license = "Apache-2.0/MIT"

[dependencies]

log = "0.3.0"
num = "0.1.18"
rand = "0.2.1"
rustc-serialize = "0.3.7"

[dependencies.bencode]
#git = "https://github.com/arjantop/rust-bencode.git"
git = "https://github.com/cheme/rust-bencode.git"

[lib]

name = "dht"
path = "src/lib.rs"
