[package]

name = "dht"
description = "Implementation of Kademlia-based DHT in Rust"
version = "0.0.1"
authors = ["Dmitry Tantsur <divius.inside@gmail.com>"]
homepage = "https://github.com/divius/rust-dht"
readme = "README.md"
license = "Apache-2.0/MIT"

[dependencies]

bencode = "~0.1.7"
log = "~0.2.1"
num = "~0.1.10"
rand = "~0.1.2"
rustc-serialize = "~0.2.10"

[lib]

name = "dht"
path = "src/lib.rs"
