[package]

name = "dht"
description = "Implementation of Kademlia-based DHT in Rust"
version = "0.0.0"
authors = ["Dmitry Tantsur <divius.inside@gmail.com>"]
homepage = "https://github.com/Divius/rust-dht"
readme = "README.md"
license = "Apache-2.0/MIT"

[dependencies]

bencode = "~0.1.0"
log = "~0.1.0"
num = "~0.1.3"
rustc-serialize = "~0.2.4"

[lib]

name = "dht"
path = "src/lib.rs"
