[package]

name = "dht"
version = "0.1.0"
authors = ["Dmitry Tantsur <divius.inside@gmail.com>"]

[dependencies.num]

;git = "https://github.com/rust-lang/num"
git = "https://github.com/gifnksm/num"

[dependencies.bencode]

git = "https://github.com/arjantop/rust-bencode"

[lib]

name = "dht"
path = "src/lib.rs"
